export const eventsStaticData = [
  {
    id: 1,
    eventName: "Tech Connect 2025",
    location: "Kathmandu, Nepal",
    time: "2025-03-15T10:00:00Z",
    organizer: "Nepal Tech Community",
    description: "A networking event for tech startups and enthusiasts.",
    image: "https://picsum.photos/seed/1/200/200",
    guests: 250,
  },
  {
    id: 2,
    eventName: "Startup Summit 2025",
    location: "Lalitpur, Nepal",
    time: "2025-04-20T09:00:00Z",
    organizer: "Startup Nepal",
    description: "A conference for early-stage startups to pitch their ideas.",
    image: "https://picsum.photos/seed/2/200/200",
    guests: 300,
  },
  {
    id: 3,
    eventName: "Music Fest Kathmandu",
    location: "Tundikhel, Kathmandu",
    time: "2025-05-05T18:00:00Z",
    organizer: "Nepal Music Lovers",
    description: "A live concert featuring local and international artists.",
    image: "https://picsum.photos/seed/3/200/200",
    guests: 5000,
  },
  {
    id: 4,
    eventName: "Artificial Intelligence Expo",
    location: "Pokhara, Nepal",
    time: "2025-06-10T11:00:00Z",
    organizer: "AI Nepal",
    description: "Showcasing AI advancements in Nepal.",
    image: "https://picsum.photos/seed/11/200/200",
    guests: 800,
  },
  {
    id: 5,
    eventName: "Food & Beverage Festival",
    location: "Bhaktapur, Nepal",
    time: "2025-07-15T15:00:00Z",
    organizer: "Nepal Foodies",
    description:
      "A festival featuring street food, beverages, and culinary arts.",
    image: "https://picsum.photos/seed/5/200/200",
    guests: 1500,
  },
  {
    id: 6,
    eventName: "Eco-Friendly Living Expo",
    location: "Lalitpur, Nepal",
    time: "2025-08-12T10:30:00Z",
    organizer: "Go Green Nepal",
    description: "Showcasing sustainable and eco-friendly lifestyle products.",
    image: "https://picsum.photos/seed/6/200/200",
    guests: 600,
  },
  {
    id: 7,
    eventName: "Nepal Coding Bootcamp",
    location: "Kathmandu, Nepal",
    time: "2025-09-20T09:00:00Z",
    organizer: "Code for Nepal",
    description: "An intensive bootcamp for aspiring software developers.",
    image: "https://picsum.photos/seed/7/200/200",
    guests: 100,
  },
  {
    id: 8,
    eventName: "Gaming Championship 2025",
    location: "Pokhara, Nepal",
    time: "2025-10-10T12:00:00Z",
    organizer: "Nepal Esports Federation",
    description: "A nationwide esports tournament with cash prizes.",
    image: "https://picsum.photos/seed/8/200/200",
    guests: 20002,
  },
  {
    id: 9,
    eventName: "Yoga and Wellness Retreat",
    location: "Nagarkot, Nepal",
    time: "2025-11-05T06:30:00Z",
    organizer: "Nepal Wellness Center",
    description: "A weekend retreat for yoga, meditation, and wellness.",
    image: "https://picsum.photos/seed/9/200/200",
    guests: 120,
  },
  {
    id: 10,
    eventName: "Blockchain and Crypto Summit",
    location: "Kathmandu, Nepal",
    time: "2025-12-10T10:00:00Z",
    organizer: "Crypto Nepal",
    description:
      "A summit discussing blockchain trends and cryptocurrency adoption.",
    image: "https://picsum.photos/seed/10/200/200",
    guests: 500,
  },
];
